In [14]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns

In [18]:
# !pip install recbole

In [7]:
pd.read_csv('./mind_train/entity_embedding.vec', sep='\t')

Q34433  0.017808  -0.073256  0.102521  -0.059926  -0.060665  \
0            Q41 -0.063388  -0.181451  0.057501  -0.091254  -0.076217   
1         Q56037  0.021550  -0.044888 -0.027872  -0.128843   0.066651   
2          Q1860  0.060958   0.069934  0.015832   0.079471  -0.023362   
3          Q7737 -0.021237   0.176011 -0.078886   0.041470   0.136488   
4         Q39631 -0.093106  -0.052002  0.020556  -0.020801   0.043180   
...          ...       ...        ...       ...        ...        ...   
42001  Q54860790  0.034682  -0.009413 -0.024317   0.073895   0.028052   
42002  Q54861457 -0.074425  -0.042263 -0.009502   0.033632  -0.092861   
42003  Q54862508 -0.052323  -0.078029 -0.060925  -0.052536   0.006802   
42004  Q54866839  0.015159   0.021187  0.059618  -0.007465  -0.038469   
42005  Q42301562 -0.005190  -0.047871  0.009753  -0.021500  -0.000049   

       0.027027  -0.091728  -0.003057  -0.170798  ...  0.013433  0.045894  \
0     -0.052525   0.050500  -0.224871  -0.018145  ...  0.001861  0.124535   
1     -0.072159   0.019879  -0.183956   0.080640  ...  0.091477  0.091388   
2     -0.125007  -0.043618   0.134063  -0.121691  ... -0.014287  0.013578   
3     -0.063177  -0.013134  -0.048977  -0.072779  ... -0.162670 -0.101399   
4     -0.072321   0.000910   0.028156   0.176303  ... -0.086840 -0.078992   
...         ...        ...        ...        ...  ...       ...       ...   
42001  0.028039   0.039260   0.017398   0.017743  ...  0.034473  0.035736   
42002 -0.067328  -0.009075   0.048518  -0.049856  ...  0.077567  0.055743   
42003 -0.070488  -0.081736   0.026385  -0.037127  ...  0.045298  0.009842   
42004  0.047728  -0.049030   0.070997  -0.063303  ...  0.013430 -0.028223   
42005 -0.010786   0.031302   0.022225  -0.022653  ... -0.014884  0.047493   

       -0.071253  0.086445  -0.120466  0.059235  -0.071865  0.058854  \
0      -0.151043 -0.263698  -0.103607  0.020007  -0.101157 -0.091567   
1      -0.027993 -0.112258  -0.231887  0.095612  -0.008997 -0.157394   
2       0.099977  0.012199  -0.141138  0.056129  -0.133727  0.025795   
3       0.039757  0.123693  -0.129503  0.153088  -0.014275 -0.113625   
4      -0.062712  0.051117  -0.184307  0.127637  -0.144866  0.044690   
...          ...       ...        ...       ...        ...       ...   
42001   0.008329 -0.049981  -0.025212 -0.018404   0.004110  0.013771   
42002  -0.035487  0.041439  -0.016274  0.031114  -0.001480 -0.057676   
42003  -0.019821 -0.033952  -0.047436  0.062752   0.043236  0.032251   
42004  -0.021695  0.025361  -0.003214  0.020141  -0.028943 -0.046590   
42005   0.060764  0.013757   0.026994  0.016827   0.024246 -0.040823   

       0.024765  Unnamed: 101  
0      0.035234           NaN  
1      0.088364           NaN  
2      0.051448           NaN  
3     -0.097839           NaN  
4      0.013498           NaN  
...         ...           ...  
42001 -0.008027           NaN  
42002 -0.018141           NaN  
42003 -0.001261           NaN  
42004 -0.027286           NaN  
42005 -0.008903           NaN  

[42006 rows x 102 columns]

In [9]:
!head ./mind_train/entity_embedding.vec

Q34433	0.017808	-0.073256	0.102521	-0.059926	-0.060665	0.027027	-0.091728	-0.003057	-0.170798	0.111819	0.006821	-0.049873	-0.050532	-0.003127	-0.074472	-0.115891	-0.067093	-0.095272	0.019178	-0.083725	-0.060890	0.017744	0.049417	-0.026014	-0.048549	0.017528	0.044163	0.022111	-0.081519	0.046278	-0.183939	-0.063143	-0.014518	-0.080644	-0.099994	0.085905	-0.083003	-0.092844	-0.216481	0.125441	0.179819	0.036735	-0.085375	0.021276	-0.154971	0.039009	0.016059	0.067725	-0.148213	0.158773	-0.028527	0.125790	0.006361	0.067541	0.077552	0.060792	-0.044511	-0.005862	-0.068080	-0.063204	-0.094127	0.115441	-0.016472	0.106616	0.047839	-0.151805	-0.111083	-0.142330	-0.120680	-0.050393	-0.073787	0.017424	-0.081620	0.062599	-0.022102	-0.102688	-0.128149	-0.075895	0.095134	0.000984	0.010143	-0.068552	-0.026573	0.019735	-0.000981	-0.126635	0.008300	0.170557	0.002250	-0.157175	-0.077962	0.013433	0.045894	-0.071253	0.086445	-0.120466	0.059235	-0.071865	0.058854	0.024765	
Q41	-0.063388	-0.181451	0.057501	-0.

In [2]:
import numpy as np

In [15]:
entity_vecs = {}

with open('./data/mind_large_train/entity_embedding.vec', 'r') as f:
    for line in f.readlines():
        tokens = line.strip().split('\t')
        entity_vecs[tokens[0]] = np.asarray(tokens[1:]).astype(np.float64)

with open('./data/mind_large_dev/entity_embedding.vec', 'r') as f:
    for line in f.readlines():
        tokens = line.strip().split('\t')
        entity_vecs[tokens[0]] = np.asarray(tokens[1:]).astype(np.float64)

In [5]:
# entity_vecs

In [7]:
import pandas as pd

In [17]:
train_news = pd.read_csv('./data/mind_large_train/news.tsv', sep='\t', names=['news_id', 'category', 'subcategory', 'title', 'abstract', 'url', 'title_entities', 'abstract_entities'])
train_news

news_id   category               subcategory  \
0        N88753  lifestyle           lifestyleroyals   
1        N45436       news  newsscienceandtechnology   
2        N23144     health                weightloss   
3        N86255     health                   medical   
4        N93187       news                 newsworld   
...         ...        ...                       ...   
101522  N115249     sports               more_sports   
101523   N64337    finance       finance-real-estate   
101524  N100102     sports                soccer_epl   
101525   N74617      autos               autossports   
101526   N56840     sports               more_sports   

                                                    title  \
0       The Brands Queen Elizabeth, Prince Charles, an...   
1         Walmart Slashes Prices on Last-Generation iPads   
2                           50 Worst Habits For Belly Fat   
3       Dispose of unwanted prescription drugs during ...   
4       The Cost of Trump's Aid Freeze in the Trenches...   
...                                                   ...   
101522  St. Dominic soccer player tries to kick cancer...   
101523  Mansion Monday: Contemporary Des Moines home i...   
101524                       How the Sounders won MLS Cup   
101525                  Best Sports Car Deals for October   
101526       Shall we dance: Sports stars shake their leg   

                                                 abstract  \
0       Shop the notebooks, jackets, and more that the...   
1       Apple's new iPad releases bring big deals on l...   
2       These seemingly harmless habits are holding yo...   
3                                                     NaN   
4       Lt. Ivan Molchanets peeked over a parapet of s...   
...                                                   ...   
101522  Sometimes, what happens on the sidelines can b...   
101523  Among the perks of this unique Des Moines home...   
101524  Mark, Jeremiah and Casey were so excited they ...   
101525                                                NaN   
101526                                                NaN   

                                                  url  \
0       https://assets.msn.com/labs/mind/AAGH0ET.html   
1       https://assets.msn.com/labs/mind/AABmf2I.html   
2       https://assets.msn.com/labs/mind/AAB19MK.html   
3       https://assets.msn.com/labs/mind/AAISxPN.html   
4       https://assets.msn.com/labs/mind/AAJgNsz.html   
...                                               ...   
101522  https://assets.msn.com/labs/mind/BBWzQnK.html   
101523  https://assets.msn.com/labs/mind/BBWzQq8.html   
101524  https://assets.msn.com/labs/mind/BBWzQuK.html   
101525  https://assets.msn.com/labs/mind/BBy5rVe.html   
101526  https://assets.msn.com/labs/mind/BBzMpnG.html   

                                           title_entities  \
0       [{"Label": "Prince Philip, Duke of Edinburgh",...   
1       [{"Label": "IPad", "Type": "J", "WikidataId": ...   
2       [{"Label": "Adipose tissue", "Type": "C", "Wik...   
3       [{"Label": "Drug Enforcement Administration", ...   
4                                                      []   
...                                                   ...   
101522                                                 []   
101523  [{"Label": "Des Moines, Iowa", "Type": "G", "W...   
101524  [{"Label": "MLS Cup", "Type": "U", "WikidataId...   
101525  [{"Label": "Peugeot RCZ", "Type": "V", "Wikida...   
101526                                                 []   

                                        abstract_entities  
0                                                      []  
1       [{"Label": "IPad", "Type": "J", "WikidataId": ...  
2       [{"Label": "Adipose tissue", "Type": "C", "Wik...  
3                                                      []  
4       [{"Label": "Ukraine", "Type": "G", "WikidataId...  
...                                                   ...  
101522                         

In [25]:
train_news['title_entities'][5]

'[]'

In [24]:
train_news['abstract_entities'][5]

'[{"Label": "National Basketball Association", "Type": "O", "WikidataId": "Q155223", "Confidence": 1.0, "OccurrenceOffsets": [40], "SurfaceForms": ["NBA"]}]'

In [26]:
import json

def get_title_emb(title_entities):
    vecs = [entity_vecs[ent['WikidataId']] for ent in json.loads(title_entities) if ent['WikidataId'] in entity_vecs]
    if len(vecs) == 0:
        return np.zeros(100)

    return ' '.join([str(x) for x in np.stack(vecs, axis=0).mean(axis=0)])



def get_abstract_emb(abstract_entities):
    vecs = [entity_vecs[ent['WikidataId']] for ent in json.loads(abstract_entities) if ent['WikidataId'] in entity_vecs]
    if len(vecs) == 0:
        return np.zeros(100)

    return ' '.join([str(x) for x in np.stack(vecs, axis=0).mean(axis=0)])

In [27]:
def get_emb_cnt(entities):
    vecs = [entity_vecs[ent['WikidataId']] for ent in json.loads(entities) if ent['WikidataId'] in entity_vecs]
    return len(vecs)

In [28]:
train_news_with_entities = train_news[~train_news['title_entities'].isna()]
train_news_with_entities = train_news_with_entities[train_news_with_entities['title_entities'].apply(get_emb_cnt) > 0]

In [30]:
train_news_with_abstract_entities = train_news[~train_news['abstract_entities'].isna()]
train_news_with_abstract_entities = train_news_with_abstract_entities[train_news_with_abstract_entities['abstract_entities'].apply(get_emb_cnt) > 0]

In [33]:
train_news_with_entities['title_emb'] = train_news_with_entities['title_entities'].apply(get_title_emb)

In [37]:
train_news_with_abstract_entities['abstract_emb'] = train_news_with_abstract_entities['abstract_entities'].apply(get_abstract_emb)

In [39]:
title_emb = train_news_with_entities.rename({'news_id': 'nid:token', 'title_emb':'title_emb:float_seq'}, axis=1)[['nid:token', 'title_emb:float_seq']]
title_emb

nid:token                                title_emb:float_seq
0         N88753  0.004057333333333334 -0.03991733333333333 -0.0...
1         N45436  -0.003665999999999999 0.010121499999999999 0.0...
2         N23144  -0.013597 -0.009758 0.01712 -0.051993 0.037963...
3         N86255  0.063956 0.003075 -0.005839 -0.026747 0.027664...
6         N99744  0.014257 0.018351 0.005199 0.001773 0.031984 0...
...          ...                                                ...
101520    N61455  0.069955 -0.007432 0.075966 0.00397 -0.087124 ...
101521   N114875  -0.005615 0.096387 -0.025957 0.094287 0.044024...
101523    N64337  -0.108383 -0.133976 -0.019564 -0.084663 -0.128...
101524   N100102  0.00011349999999999902 0.0340165 0.00024800000...
101525    N74617  -0.002495 0.002657 -0.026376 -0.060487 -0.0160...

[74874 rows x 2 columns]

In [42]:
abstract_emb = train_news_with_abstract_entities.rename({'news_id': 'aid:token', 'abstract_emb':'abstract_emb:float_seq'}, axis=1)[['aid:token', 'abstract_emb:float_seq']]

In [43]:
abstract_emb

aid:token                             abstract_emb:float_seq
1         N45436  0.0259735 -0.0055585 0.038956 -0.0096219999999...
2         N23144  -0.013597 -0.009758 0.01712 -0.051993 0.037963...
4         N93187  -0.065324 -0.088163 -0.015203 -0.031949 0.0912...
5         N75236  0.003752 -0.061771 -0.037073 0.02677 -0.090658...
6         N99744  -0.008593666666666668 -0.00016800000000000032 ...
...          ...                                                ...
101517    N45647  -0.04856875 -0.02458275 0.01521025 -0.0313645 ...
101518   N129155  0.063972 0.041784 0.043465000000000004 0.00347...
101519    N97700  0.055938 -0.002104 0.03155 -0.022865 -0.043783...
101521   N114875  -0.010276833333333332 0.033702833333333335 -0....
101523    N64337  -0.108383 -0.133976 -0.019564 -0.084663 -0.128...

[75671 rows x 2 columns]

In [44]:
!mkdir recbox_data

abstract_emb.to_csv('./data/preprocessed/mind_large/mind_large.absemb', index=False, sep='\t')

A subdirectory or file recbox_data already exists.


model

In [1]:
import torch
from torch import nn

from recbole.model.abstract_recommender import SequentialRecommender
from recbole.model.init import xavier_normal_initialization
from recbole.model.layers import FeatureSeqEmbLayer
from recbole.model.loss import BPRLoss


class GRU4RecExt(SequentialRecommender):
    def __init__(self, config, dataset):
        super(GRU4RecExt, self).__init__(config, dataset)

        # load parameters info
        self.embedding_size = config['embedding_size']
        self.hidden_size = config['hidden_size']
        self.num_layers = config['num_layers']
        self.dropout_prob = config['dropout_prob']

        #self.selected_features = config['selected_features']
        #self.pooling_mode = config['pooling_mode']
        self.device = config['device']
        #self.num_feature_field = len(config['selected_features'])

        self.loss_type = config['loss_type']

        # define layers and loss
        self.item_embedding = nn.Embedding(self.n_items, self.embedding_size, padding_idx=0)

        pretrained_news_emb = dataset.get_preload_weight('nid')
        self.feature_embed_layer = nn.Embedding.from_pretrained(torch.from_numpy(pretrained_news_emb).to(dtype=torch.float))
        self.feature_embed_size = self.feature_embed_layer.embedding_dim

        self.item_gru_layers = nn.GRU(
            input_size=self.embedding_size,
            hidden_size=self.hidden_size,
            num_layers=self.num_layers,
            bias=False,
            batch_first=True,
        )
        # For simplicity, we use same architecture for item_gru and feature_gru
        self.feature_gru_layers = nn.GRU(
            input_size=self.feature_embed_size,
            hidden_size=self.hidden_size,
            num_layers=self.num_layers,
            bias=False,
            batch_first=True,
        )
        self.dense_layer = nn.Linear(self.hidden_size * 2, self.embedding_size)
        self.dropout = nn.Dropout(self.dropout_prob)
        if self.loss_type == 'BPR':
            self.loss_fct = BPRLoss()
        elif self.loss_type == 'CE':
            self.loss_fct = nn.CrossEntropyLoss()
        else:
            raise NotImplementedError("Make sure 'loss_type' in ['BPR', 'CE']!")

        # parameters initialization
        self.apply(xavier_normal_initialization)
        self.other_parameter_name = ['feature_embed_layer']

    def forward(self, item_seq, item_seq_len):
        item_seq_emb = self.item_embedding(item_seq)
        item_seq_emb_dropout = self.dropout(item_seq_emb)
        item_gru_output, _ = self.item_gru_layers(item_seq_emb_dropout)  # [B Len H]

        feature_seq_emb = self.feature_embed_layer(item_seq)
        feature_gru_output, _ = self.feature_gru_layers(feature_seq_emb)  # [B Len H]

        output_concat = torch.cat((item_gru_output, feature_gru_output), -1)  # [B Len 2*H]
        output = self.dense_layer(output_concat)
        output = self.gather_indexes(output, item_seq_len - 1)  # [B H]
        return output  # [B H]

    def calculate_loss(self, interaction):
        item_seq = interaction[self.ITEM_SEQ]
        item_seq_len = interaction[self.ITEM_SEQ_LEN]
        seq_output = self.forward(item_seq, item_seq_len)
        pos_items = interaction[self.POS_ITEM_ID]
        if self.loss_type == 'BPR':
            neg_items = interaction[self.NEG_ITEM_ID]
            pos_items_emb = self.item_embedding(pos_items)  # [B H]
            neg_items_emb = self.item_embedding(neg_items)  # [B H]
            pos_score = torch.sum(seq_output * pos_items_emb, dim=-1)  # [B]
            neg_score = torch.sum(seq_output * neg_items_emb, dim=-1)  # [B]
            loss = self.loss_fct(pos_score, neg_score)
            return loss
        else:  # self.loss_type = 'CE'
            test_item_emb = self.item_embedding.weight
            logits = torch.matmul(seq_output, test_item_emb.transpose(0, 1))
            loss = self.loss_fct(logits, pos_items)
            return loss

    def predict(self, interaction):
        item_seq = interaction[self.ITEM_SEQ]
        item_seq_len = interaction[self.ITEM_SEQ_LEN]
        test_item = interaction[self.ITEM_ID]
        seq_output = self.forward(item_seq, item_seq_len)
        test_item_emb = self.item_embedding(test_item)
        scores = torch.mul(seq_output, test_item_emb).sum(dim=1)  # [B]
        return scores

    def full_sort_predict(self, interaction):
        item_seq = interaction[self.ITEM_SEQ]
        item_seq_len = interaction[self.ITEM_SEQ_LEN]
        seq_output = self.forward(item_seq, item_seq_len)
        test_items_emb = self.item_embedding.weight
        scores = torch.matmul(seq_output, test_items_emb.transpose(0, 1))  # [B n_items]
        return scores

In [94]:
!gdown 1aIZ7ZvochkW32utP5Q1QNVrDMdFRv-2h -O 'mind_small.inter'

Downloading...
From: https://drive.google.com/uc?id=1aIZ7ZvochkW32utP5Q1QNVrDMdFRv-2h
To: /content/mind_small.inter
100% 212M/212M [00:03<00:00, 59.4MB/s]


In [95]:
!head mind_small.inter

user_id:token	item_id:token	label:float	timestamp:float
13740	55689	1	1573452358
13740	35729	0	1573452358
91836	20678	0	1573571490
91836	39317	0	1573571490
91836	58114	0	1573571490
91836	20495	0	1573571490
91836	42977	0	1573571490
91836	22407	0	1573571490
91836	14592	0	1573571490


In [13]:
import logging
from logging import getLogger
from recbole.config import Config
from recbole.data import create_dataset, data_preparation
from recbole.model.sequential_recommender import GRU4Rec
from recbole.trainer import Trainer
from recbole.utils import init_seed, init_logger

In [14]:
from utils.utils import load_config
parameter_dict = load_config('./configs/sequential/gru4rec.yaml')

config = Config(model='GRU4Rec', dataset='mind_small', config_dict=parameter_dict)

# init random seed
init_seed(config['seed'], config['reproducibility'])

# logger initialization
init_logger(config)
logger = getLogger()
# Create handlers
c_handler = logging.StreamHandler()
c_handler.setLevel(logging.INFO)
logger.addHandler(c_handler)

# write config info into log
logger.info(config)

04 Jun 19:42    INFO  
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = data/preprocessed\mind_small
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = True

Training Hyper Parameters:
epochs = 10
train_batch_size = 1024
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'none', 'sample_num': 'none', 'alpha': 'none', 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'group_by': 'user', 'order': 'TO', 'mode': 'uni10'}
repeatable = True
metrics = ['Precision', 'Recall', 'NDCG', 'MAP']
topk = [1, 2, 5, 7, 10]
valid_metric = NDCG@10
valid_metric_bigger = True
eval_batch_size = 1024
metric_decimal_place = 4

Dataset Hyper Parameters:
field_

In [15]:
config


General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = data/preprocessed\mind_small
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = True

Training Hyper Parameters:
epochs = 10
train_batch_size = 1024
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'none', 'sample_num': 'none', 'alpha': 'none', 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'group_by': 'user', 'order': 'TO', 'mode': 'uni10'}
repeatable = True
metrics = ['Precision', 'Recall', 'NDCG', 'MAP']
topk = [1, 2, 5, 7, 10]
valid_metric = NDCG@10
valid_metric_bigger = True
eval_batch_size = 1024
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator = 	
seq_sepa

In [16]:
dataset = create_dataset(config)
logger.info(dataset)

ValueError: File data/preprocessed\mind_small\mind_small..inter not exist.

In [8]:
import pandas as pd

pd.read_csv("./data/preprocessed/mind_small/mind_small.inter", sep='\t')

user_id:token  item_id:token  label:float  timestamp:float
0                13740          55689            1       1573452358
1                13740          35729            0       1573452358
2                91836          20678            0       1573571490
3                91836          39317            0       1573571490
4                91836          58114            0       1573571490
...                ...            ...          ...              ...
8584437          68182          48740            0       1573808074
8584438          68182          55237            0       1573808074
8584439          68182          31958            0       1573808074
8584440          68182          29091            0       1573808074
8584441          68182          24802            0       1573808074

[8584442 rows x 4 columns]

In [5]:
%load_ext autoreload
%autoreload 2

In [10]:
from utils.dataloader_utils import data_preparation
from utils.sampler import RepeatableSamplerCustom, RepeatableSampler

In [7]:
phases = ["train", "valid", "test"]
# sampler = RepeatableSamplerCustom(phases, dataset,
#                 config["train_neg_sample_args"]["distribution"],
#                 config["train_neg_sample_args"]["alpha"],
#             )


sampler = RepeatableSampler(phases, dataset,
                config["train_neg_sample_args"]["distribution"],
                config["train_neg_sample_args"]["alpha"],
            )

In [6]:
# dataset splitting
train_data, valid_data, test_data = data_preparation(config, dataset)#, sampler=sampler)

28 May 13:51    INFO  [Training]: train_batch_size = [1024] train_neg_sample_args: [{'distribution': 'none', 'sample_num': 'none', 'alpha': 'none', 'dynamic': False, 'candidate_num': 0}]
[Training]: train_batch_size = [1024] train_neg_sample_args: [{'distribution': 'none', 'sample_num': 'none', 'alpha': 'none', 'dynamic': False, 'candidate_num': 0}]
28 May 13:51    INFO  [Evaluation]: eval_batch_size = [1024] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'group_by': 'user', 'order': 'TO', 'mode': 'uni10'}]
[Evaluation]: eval_batch_size = [1024] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'group_by': 'user', 'order': 'TO', 'mode': 'uni10'}]


In [7]:
valid_data._sampler

In [8]:
valid_data._dataset.inter_feat['user_id']

tensor([    1,     1,     1,  ..., 94056, 94056, 94057])

In [9]:
valid_data._dataset.inter_feat['item_id']

tensor([  942,  4690,  3270,  ..., 20331, 21826,  8362])

In [10]:
valid_data._dataset.inter_feat["label_list"]

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [13]:
valid_data.collate_fn([20])[0]['label']

tensor([1., 1., 1.,  ..., 0., 0., 0.])

In [16]:
train_data.collate_fn([0])['label_list']

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.]])

In [9]:
train_data.collate_fn([100])['item_id_list']

tensor([[2166,  787, 1421, 4225, 1707, 1089, 4257, 5025, 4165, 1424, 1041, 3265,
         3510,  942,  523, 2379, 2527,  233, 1775, 1333, 2578,  738, 2579,  745,
          289,  741, 2320,  699, 1699, 1707,  527, 2595, 1533,  547, 1537,  221,
          554, 1975,  377,  775, 2998,  677,  760,  635, 1547,  662,  697, 1483,
          552, 2957]])

In [10]:
train_data.collate_fn([100])['label_list']

tensor([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
train_data.sampler = None

ValueError: sampler attribute should not be set after TrainDataLoader is initialized

In [7]:
# model loading and initialization
model = GRU4RecExt(config, train_data.dataset).to(config['device'])
logger.info(model)

# trainer loading and initialization
trainer = Trainer(config, model)

# model training
best_valid_score, best_valid_result = trainer.fit(train_data, valid_data=valid_data, show_progress=True)

09 May 17:21    INFO  GRU4RecExt(
  (item_embedding): Embedding(97646, 64, padding_idx=0)
  (feature_embed_layer): Embedding(97646, 100)
  (item_gru_layers): GRU(64, 64, bias=False, batch_first=True)
  (feature_gru_layers): GRU(100, 64, bias=False, batch_first=True)
  (dense_layer): Linear(in_features=128, out_features=64, bias=True)
  (dropout): Dropout(p=0.3, inplace=False)
  (loss_fct): CrossEntropyLoss()
)
Trainable parameters: 6313664
GRU4RecExt(
  (item_embedding): Embedding(97646, 64, padding_idx=0)
  (feature_embed_layer): Embedding(97646, 100)
  (item_gru_layers): GRU(64, 64, bias=False, batch_first=True)
  (feature_gru_layers): GRU(100, 64, bias=False, batch_first=True)
  (dense_layer): Linear(in_features=128, out_features=64, bias=True)
  (dropout): Dropout(p=0.3, inplace=False)
  (loss_fct): CrossEntropyLoss()
)
Trainable parameters: 6313664
09 May 17:21    ERROR  Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment va

Train     0:   0%|                                                         | 0/6693 [00:00<?, ?it/s]